---
title: "ConfirmalInference"
format: html
---

# SetUp


```{r}
set.seed(111)
pacman::p_load(
  tidyverse,
  cfcausal
  )

Data <- arrow::read_parquet(
  "Public/Example.parquet"
  ) |> 
  filter(Tenure >= 10) |> 
  filter(Tenure <= quantile(Tenure,0.95)
         ) |> 
  filter(Size <= quantile(Size,0.95) &
           Size >= quantile(Size,0.05)
         ) |> 
  filter(DistanceStation <= quantile(DistanceStation,0.95) &
           DistanceStation >= quantile(DistanceStation,0.05)
         ) |> 
  filter(RoomNum <= quantile(RoomNum,0.95) &
           RoomNum >= quantile(RoomNum,0.05)
         ) |> 
  filter(Youseki <= quantile(Youseki,0.95) &
           Youseki >= quantile(Youseki,0.05)
         ) |> 
  filter(Kenpei <= quantile(Kenpei,0.95) &
           Kenpei >= quantile(Kenpei,0.05)
         )

summary(Data)

```


## After

```{r}
Y <- Data$Price
W <- Data$Reform
X <- Data |> 
  select(
    -Price,
    -Reform
    )

Group <- sample(0:1,length(Y),replace = TRUE)

CIfun <- conformalIte(
  X[Group == 0,], 
  Y[Group == 0], 
  W[Group == 0], 
  alpha = 0.1, 
  algo = "nest", 
  exact = FALSE, 
  type = "CQR",
  quantiles = c(0.05, 0.95), 
  outfun = "quantRF", 
  useCV = FALSE
  )


Result <- X[Group == 1,] |> 
  mutate(
    Lower = CIfun(X[Group == 1,])[1],
    Upper = CIfun(X[Group == 1,])[2]
  )

```

