---
title: "Example: Cross fitting and it's applications"
subtitle: "機械学習の経済学への応用"
author: "川田恵介"
format:
  revealjs:
    incremental: true
    self-contained-math: true
    slide-number: true
execute: 
  message: false
  warning: false
  echo: true
  eval: true
bibliography: references.bib
---

## 交差推定 (Cross fitting)

- "交差推定"は機械学習の応用において、極めて重要

    - 予測問題: HyperParameter Tuning, Algorithm選択, Stacking
    
    - 母集団の推論: 収束性質の改善

- しっかりイメージを持つことが重要


    - 現代的パッケージを用いると(べきだが)、イメージしにくいかも、、、
    
## 例: 元データ

```{r}
library(tidyverse)
library(magrittr)

Data <- tibble(
  X = c(4, 2, 1, 1, 2, 5),
  Y = c(10, 19, 10, 2, 10, 20)
)

Data
```

## 例: グループ分け

```{r}
Data <- mutate(Data,
               G = sample(1:3,6,replace = TRUE)
               )

Data
```

## 例: G = 1への予測値

```{r}
tibble(X = c(4,2,1,1,2,5),
       Y = c(10,19,10,2,10,20),
       G = c(1,2,1,3,3,2),
       MeanPrediction = c(12.75,NA,12.75,NA,NA,NA),
       KawataPrediction = c(10,NA,9,NA,NA,NA)
       )
```

## 例: G = 2への予測値

```{r}
tibble(X = c(4,2,1,1,2,5),
       Y = c(10,19,10,2,10,20),
       G = c(1,2,1,3,3,2),
       MeanPrediction = c(12.75,8,12.75,NA,NA,8),
       KawataPrediction = c(10,10,9,NA,NA,5)
       )
```


## 例: G = 3への予測値

```{r}
tibble(X = c(4,2,1,1,2,5),
       Y = c(10,19,10,2,10,20),
       G = c(1,2,1,3,3,2),
       MeanPrediction = c(12.75,8,12.75,14.75,14.75,8),
       KawataPrediction = c(10,10,9,10,20,5)
       )
```

- 交差推定完了!!!

## 例: Algorithm比較

```{r}
tibble(X = c(4,2,1,1,2,5),
       Y = c(10,19,10,2,10,20),
       G = c(1,2,1,3,3,2),
       MeanPrediction = c(12.75,8,12.75,14.75,14.75,8),
       KawataPrediction = c(10,10,9,10,20,5)
       ) |> 
  mutate(MeanEval = (Y - MeanPrediction)^2,
         KawataEval = (Y - KawataPrediction)^2)
```

## 例: Stacking

```{r}
tibble(X = c(4,2,1,1,2,5),
       Y = c(10,19,10,2,10,20),
       G = c(1,2,1,3,3,2),
       MeanPrediction = c(12.75,8,12.75,14.75,14.75,8),
       KawataPrediction = c(10,10,9,10,20,5)
       ) %$%
  lm(Y ~ MeanPrediction + KawataPrediction)
```
